#!/bin/bash
BRANCH_NAME=$(git branch | grep '*' | sed 's/.*\///g' | grep -o '^\(.[A-Za-z][A-Za-z]*-[0-9][0-9]*\)')
if [ ! -z "$BRANCH_NAME" ] && ! grep "\[$BRANCH_NAME\]" "$1"; then
  sed -i "1s/^/\[$BRANCH_NAME\] /" $1
fi
